---
- name: install and start apache
  hosts: all
  vars:    
    http_port: 80    
    max_clients: 200
  remote_user: root

  tasks:

  - name: stop httpd
    service: name=httpd state=stopped enabled=no

  - name: remove config file
    file: dest=/etc/httpd/conf/httpd.conf state=absent

  - name: remove httpd
    yum: pkg=httpd state=absent


