---
- name: install and start apache
  hosts: all
  vars:    
    http_port: 8080    
    max_clients: 200
  remote_user: root

  tasks:
  - name: install httpd
    yum: pkg=httpd state=latest

  - name: write the apache config file     
    template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
    notify: start httpd

  handlers:
  - name: start httpd
    service: name=httpd state=restarted

